version: '3.8'

services:
  crmappservice:
    build:
        context: ./CRM.ApiService
        dockerfile: Dockerfile
    ports:
     - "57607:8080" 
 
  cxnoneappservice: 
    build:
        context: ./CXnone.ApiService
        dockerfile: Dockerfile
    ports:
     - "57606:5000"
    environment:
     - ASPNETCORE_URLS=http://+:5000

  clientconsole:
    image: client
    build:
      context: ./Client.Console
      dockerfile: Dockerfile
    depends_on:
     - crmappservice
     - cxnoneappservice
    environment:
     - CRM_API_URL=http://crmappservice:8080
     - CXNONE_API_URL=http://cxnoneappservice:5000

